services:

##########################################
##
## shinobi / cloud ubuntu desktop
##
##########################################

    cloud-ubuntu-desktop:

        container_name: cloud-ubuntu-desktop

        hostname: urus

        image: softwareshinobi/cloud-ubuntu-desktop

        restart: unless-stopped

        build: 

            context: .

            dockerfile: Dockerfile

        volumes:

            - /tmp/volumes/urus/shinobi:/home/shinobi

        domainname: desktop.softwareshinobi.digital

        ports:

            - "5922:22"

            - "5980:80"

            - "5900:5900"

        environment:
        
            TZ: America/Bogota

            USER_UID: 1000

            USER_GID: 1000

            USER: shinobi

            PASSWORD: shinobi

            HTTP_PASSWORD: shinobi

            VIRTUAL_HOST: desktop.softwareshinobi.digital

            LETSENCRYPT_HOST: desktop.softwareshinobi.digital
            
