services:

##########################################
##
## shinobi / cloud ubuntu desktop
##
##########################################

    cloud-ubuntu-desktop:

        container_name: cloud-ubuntu-desktop

        image: softwareshinobi/cloud-ubuntu-desktop

        restart: unless-stopped

        build: 

            context: .

            dockerfile: Dockerfile

        volumes:

            - /tmp/volumes/desktop/shinobi:/home/shinobi

        hostname: desktop

        domainname: desktop.softwareshinobi.digital

        ports:

            - "127.0.0.1:5922:22"

            - "127.0.0.1:5980:80"

            - "127.0.0.1:5900:5900"

        environment:
        
            TZ: America/Bogota

            USER_UID: 1000

            USER_GID: 1000

            USER: shinobi

            PASSWORD: shinobi

            HTTP_PASSWORD: shinobi

            VIRTUAL_HOST: desktop.softwareshinobi.digital

            LETSENCRYPT_HOST: desktop.softwareshinobi.digital
            
